[project]
name = "pdf-compression"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
"pymupdf>=1.24.0",
"pillow>=10.0.0",
"pyvips>=2.2.3",
"pyvips-binary>=2.2.3",
"pyinstaller>=6.0.0"
]
